"""Map normalized Instagram captions to broadcast description candidates.

Input is `shows/convergence-zone/playlists/sources/instagram/promos.json`, generated by
`fetch_instagram_promos.py` (or by a manual import that writes the same shape).
"""
import datetime as dt
import json
import re

from paths import INSTAGRAM_PROMOS

DATE_PATTERNS = (
    re.compile(r"\b(20\d{2})-(\d{2})-(\d{2})\b"),
    re.compile(r"\b(\d{1,2})[./-](\d{1,2})[./-](20\d{2})\b"),
    re.compile(
        r"\b("
        r"january|february|march|april|may|june|july|august|"
        r"september|october|november|december"
        r")\s+(\d{1,2})(?:st|nd|rd|th)?(?:,\s*|\s+)(20\d{2})\b",
        re.I,
    ),
)

MONTHS = {
    "january": 1, "february": 2, "march": 3, "april": 4, "may": 5, "june": 6,
    "july": 7, "august": 8, "september": 9, "october": 10, "november": 11, "december": 12,
}

POSITIVE_RE = re.compile(
    r"convergence\s*zone|this week|tonight|tuesday|kser|kxir|streaming|show", re.I
)
NOISE_RE = re.compile(
    r"(link in bio|tunein|donate|membership|archives?|bandcamp|spotify|tidal)\b", re.I
)
HASHTAG_RE = re.compile(r"(?:^|\s)#\w+")


def _parse_ts(raw):
    if not raw:
        return None
    s = str(raw).strip()
    if not s:
        return None
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    for fn in (dt.datetime.fromisoformat,):
        try:
            return fn(s)
        except ValueError:
            pass
    try:
        return dt.datetime.fromtimestamp(int(s), tz=dt.timezone.utc)
    except (TypeError, ValueError, OSError):
        return None


def _clean_caption(text):
    lines = [ln.strip() for ln in str(text or "").replace("\r\n", "\n").split("\n")]
    kept = [ln for ln in lines if ln]
    if not kept:
        return ""
    while kept and (NOISE_RE.search(kept[-1]) or HASHTAG_RE.search(kept[-1])):
        kept.pop()
    return "\n\n".join(kept).strip()


def _score(text):
    if not text:
        return 0.0
    score = 0.0
    if len(text) >= 120:
        score += 0.35
    if len(text.split()) >= 16:
        score += 0.2
    if POSITIVE_RE.search(text):
        score += 0.35
    if text.count("\n\n") >= 1 or text.count(".") >= 2:
        score += 0.1
    return round(min(score, 1.0), 2)


def _caption_dates(caption):
    out = []
    for pat in DATE_PATTERNS:
        for m in pat.finditer(caption):
            try:
                if pat is DATE_PATTERNS[0]:
                    out.append(dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3))))
                elif pat is DATE_PATTERNS[1]:
                    out.append(dt.date(int(m.group(3)), int(m.group(1)), int(m.group(2))))
                else:
                    mo = MONTHS[m.group(1).lower()]
                    out.append(dt.date(int(m.group(3)), mo, int(m.group(2))))
            except ValueError:
                continue
    return out


def _assign_broadcast(post_dt, caption, broadcast_dates):
    valid = sorted(dt.date.fromisoformat(d) for d in broadcast_dates)
    valid_set = {d.isoformat() for d in valid}
    for cand in _caption_dates(caption):
        if cand.isoformat() in valid_set:
            return cand.isoformat(), "caption_date"

    if post_dt is None:
        return None, "none"
    d = post_dt.date()

    # Promo copy is usually posted before or on the show day; choose the next broadcast
    # in a one-week window.
    future = [x for x in valid if 0 <= (x - d).days <= 7]
    if future:
        return future[0].isoformat(), "post_date_next_tuesday"

    # Fallback for late posts that recap shortly after airing.
    past = [x for x in valid if 0 <= (d - x).days <= 2]
    if past:
        return past[-1].isoformat(), "post_date_recent_recap"
    return None, "none"


def load(broadcast_dates, promos_path=INSTAGRAM_PROMOS):
    """Returns {broadcast_date: {file, candidate, rejected, score, source, ...}}."""
    if not promos_path.exists():
        return {}

    payload = json.loads(promos_path.read_text(encoding="utf-8"))
    posts = payload.get("posts") or []
    out = {}
    for p in posts:
        caption_raw = p.get("caption") or ""
        caption = _clean_caption(caption_raw)
        score = _score(caption)
        if not caption or score < 0.35:
            continue

        target, basis = _assign_broadcast(_parse_ts(p.get("timestamp")), caption, broadcast_dates)
        if target is None:
            continue

        entry = {
            "file": f"instagram:{p.get('id') or 'unknown'}",
            "candidate": caption,
            "rejected": "",
            "score": score,
            "source": "instagram",
            "source_file": str(promos_path),
            "post_id": str(p.get("id") or ""),
            "permalink": str(p.get("permalink") or ""),
            "match_basis": basis,
            "timestamp": str(p.get("timestamp") or ""),
        }
        prior = out.get(target)
        if prior is None or entry["score"] > prior["score"]:
            out[target] = entry
    return out


if __name__ == "__main__":
    import load_spinitron

    bcs, _, _ = load_spinitron.load()
    promos = load({b["date"] for b in bcs.values()})
    print(f"instagram promo candidates mapped: {len(promos)}")
    for d, p in sorted(promos.items())[:8]:
        print(f"{d} score={p['score']} basis={p['match_basis']} id={p['post_id']}")
